---
ng_soar_queue_config: /etc/ng-soar/queues.yaml
ng_soar_queues:
  - name: enrichment
    type: rabbitmq
    durable: true
    prefetch: 10
  - name: containment
    type: rabbitmq
    durable: true
    prefetch: 5
ng_soar_integrations:
  - name: siem_ingest
    type: rest
    endpoint: https://ng-siem.internal/api/playbooks
    token: changeme
  - name: cacao_broker
    type: kafka
    brokers:
      - kafka1.internal:9092
      - kafka2.internal:9092
    topic: cacao.playbooks
ng_soar_healthcheck:
  url: http://127.0.0.1:8080/healthz
  status_code: 200

ng_soar_containerized: true

ng_soar_compose_source:
  type: smb
  share: "//10.250.232.198/shared"
  mount_point: /mnt/ng-soar
  mount_opts: guest,vers=3.0
  compose_path: /mnt/ng-soar/ng-soar/docker-compose.yml
  archive_path: /mnt/ng-soar/ng-soar/docker-compose.zip
  archive: false
  destination_dir: /opt/ng-soar

ng_soar_registry:
  url: https://index.docker.io/v1/
  username: ""
  password: ""

ng_soar_external_services:
  misp:
    host: 10.250.10.50
    port: 443
    api_base: https://misp.internal
  dfir_iris:
    host: 10.250.10.60
    port: 443
    api_base: https://dfir-iris.internal
  cortex:
    host: 10.250.10.70
    port: 9001
    api_base: http://cortex.internal:9001
